default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: challenge_app_development

test:
  <<: *default
  database: challenge_app_test

production:
  <<: *default
  database: challenge_app_production
  username: challenge_app
  password: <%= ENV["CHALLENGE_APP_DATABASE_PASSWORD"] %>
